### ISSUE TITLE
Line Break

### ISSUE THREAD

**Issue by Dari-Jones** [pgorripati1/SubmitAtEase-UI#4]
For JavaScript references, consider putting the src, integrity, and crossorigin sections on separate lines to improve readability.

Example:
```
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
```

https://github.com/pgorripati1/SubmitAtEase-UI/blob/9580e032e81f8a05a738694e3df75064d9e6cd6e/UI/authoraccount.php#L92

**Comment by pgorripati1** [comment]
It is being adjusted by Visual Studio IDE to format the document for readability.
