### ISSUE TITLE
Consider moving hard-coded credentials

### ISSUE THREAD

**Issue by Dari-Jones** [pgorripati1/SubmitAtEase-UI#5]
I understand that this code could be put into your public repo for the sake of peer revision and this course. However, perhaps putting the credentials into a less web-accessible location. I've referenced an article that may be helpful. https://www.codementor.io/ccornutt/keeping-credentials-secure-in-php-kvcbrk55z

https://github.com/pgorripati1/SubmitAtEase-UI/blob/9580e032e81f8a05a738694e3df75064d9e6cd6e/UI/dbconnect.php#L1

**Comment by pgorripati1** [comment]
Using a web user is of limited access to DB & the password is in service layers on the server.
